### PR TITLE
add dialog to enter optional prompt in krita for txt2img and img2img

### PR DESCRIPTION
**Pull request by SirFinley**
This adds dialogs for txt2img and img2img in krita to let you enter a prompt. If left blank it will use the prompt from the krita_config.yaml file.
It also adds krita/input,output folders to .gitignore

### CODE REVIEW

**Comment by sddebz** [comment]
Hi. Thank you for request. The prompt dialog is cool. 

However I see two small problems with it right now:
1. It breaks workflow where you repeatedly press hotkey to generate new outputs. Instead of just pressing hotkeys you will need to press Enter to skip dialog. I see two solutions here: add feature flag in krita_config.yaml so user can decide on using it or not OR add additional hotkey for dialog, where you can define your own options and run SD. I'll probably add such a dialog anyway this weekend.
2. It removes some code that creates filter mask in Krita. Well maybe this functionality just suck, but I would prefer to hide it behind feature flag too. Without it you'll need to manually create mask layer if your selection is not rectangular. Also selection can be feathered to automatically create smooth transition between old picture and new SD output. The QTimer there is just a workaround to get over some Krita plugin api bug.

**Comment by 1blackbar** [comment]
HEy can you enable issues panel so we can give you some feedback? I wanted ot say this works pretty great so far.
I have some small issues with lasso working just once, you have to create new lassso path everytime even tho its already created from previous ctr+alt+ W
so when you do img2img once with mask made by lassso, and you want to synthesize again immediately then it just ignores lasso mask, can you look into it ? it works fast when mask is active but when you do img2img again then its slowly synthesizing whole image which means lasso mask is ignored .

**Comment by sddebz** [comment]
I've enabled issues panel.

Lasso thing seems to be a bug, I've never actually tried lasso, will look into it.

Inpainting is actually very nice. I wanted to add it too, but didn't find the right model. Thank you for the link. However adding it will probably take some time. Webui doesn't have it yet I think and there is a problem with fitting both models on GPU. So we will probably need some switch here.

**Comment by 1blackbar** [comment]
Theres also other inpainting called LAMA ,im using it often maybe it might be ableto be incluided somehow ? Works pretty fast with gradio gui as well  heres the repo im using https://github.com/Sanster/lama-cleaner
Its not the same as SD but it works and has 3 models so far.

**Comment by sddebz** [comment]
I'll close this request because it's possible to enter prompt in Krita window now without using yaml.

**Pull request closed without merging**
